from pydantic import BaseModel

class HAR(BaseModel):
  
  
  tBodyAccDmeanBDX: float 
  tBodyAccDmeanBDY: float
  tBodyAccDmeanBDZ: float
  tBodyAccDstdBDX:  float
  tBodyAccDstdBDY:  float
  tBodyAccDstdBDZ:  float
  tBodyAccDmadBDX:  float
  tBodyAccDmadBDY:  float
  tBodyAccDmadBDZ:  float
  tBodyAccDmaxBDX:  float
  tBodyAccDmaxBDY:  float
  tBodyAccDmaxBDZ:  float
  tBodyAccDminBDX:  float
  tBodyAccDminBDY:  float
  tBodyAccDminBDZ:  float
  tBodyAccDsmaB:    float
  tBodyAccDenergyBDX: float
  tBodyAccDenergyBDY: float
  tBodyAccDenergyBDZ: float
  tBodyAccDiqrBDX:     float
  tBodyAccDiqrBDY:     float
  tBodyAccDiqrBDZ:      float
  tBodyAccDentropyBDX:  float
  tBodyAccDentropyBDY:  float
  tBodyAccDentropyBDZ:  float
  tBodyAccDarCoeffBDXC1: float
  tBodyAccDarCoeffBDXC2: float
  tBodyAccDarCoeffBDXC3: float
  tBodyAccDarCoeffBDXC4: float
  tBodyAccDarCoeffBDYC1: float
  tBodyAccDarCoeffBDYC2: float
  tBodyAccDarCoeffBDYC3: float
  tBodyAccDarCoeffBDYC4: float
  tBodyAccDarCoeffBDZC1: float
  tBodyAccDarCoeffBDZC2: float
  tBodyAccDarCoeffBDZC3: float
  tBodyAccDarCoeffBDZC4: float
  tBodyAccDcorrelationBDXCY: float
  tBodyAccDcorrelationBDXCZ: float
  tBodyAccDcorrelationBDYCZ: float
  tGravityAccDmeanBDX: float
  tGravityAccDmeanBDY: float
  tGravityAccDmeanBDZ: float
  tGravityAccDstdBDX:  float
  tGravityAccDstdBDY:  float
  tGravityAccDstdBDZ:  float
  tGravityAccDmadBDX:  float
  tGravityAccDmadBDY:  float
  tGravityAccDmadBDZ:  float
  tGravityAccDmaxBDX:  float
  tGravityAccDmaxBDY:  float
  tGravityAccDmaxBDZ:  float
  tGravityAccDminBDX:  float
  tGravityAccDminBDY:  float
  tGravityAccDminBDZ:  float
  tGravityAccDsmaB:    float
  tGravityAccDenergyBDX: float
  tGravityAccDenergyBDY: float
  tGravityAccDenergyBDZ: float
  tGravityAccDiqrBDX:  float
  tGravityAccDiqrBDY:  float
  tGravityAccDiqrBDZ:  float
  tGravityAccDentropyBDX: float
  tGravityAccDentropyBDY: float
  tGravityAccDentropyBDZ: float
  tGravityAccDarCoeffBDXC1: float
  tGravityAccDarCoeffBDXC2: float
  tGravityAccDarCoeffBDXC3: float
  tGravityAccDarCoeffBDXC4: float
  tGravityAccDarCoeffBDYC1: float
  tGravityAccDarCoeffBDYC2: float
  tGravityAccDarCoeffBDYC3: float
  tGravityAccDarCoeffBDYC4: float
  tGravityAccDarCoeffBDZC1: float
  tGravityAccDarCoeffBDZC2: float
  tGravityAccDarCoeffBDZC3: float
  tGravityAccDarCoeffBDZC4: float
  tGravityAccDcorrelationBDXCY: float
  tGravityAccDcorrelationBDXCZ: float
  tGravityAccDcorrelationBDYCZ: float
  tBodyAccJerkDmeanBDX: float
  tBodyAccJerkDmeanBDY: float
  tBodyAccJerkDmeanBDZ: float
  tBodyAccJerkDstdBDX: float
  tBodyAccJerkDstdBDY: float
  tBodyAccJerkDstdBDZ: float
  tBodyAccJerkDmadBDX: float
  tBodyAccJerkDmadBDY: float
  tBodyAccJerkDmadBDZ: float
  tBodyAccJerkDmaxBDX: float
  tBodyAccJerkDmaxBDY: float
  tBodyAccJerkDmaxBDZ: float
  tBodyAccJerkDminBDX: float
  tBodyAccJerkDminBDY: float
  tBodyAccJerkDminBDZ: float
  tBodyAccJerkDsmaB: float
  tBodyAccJerkDenergyBDX: float
  tBodyAccJerkDenergyBDY: float
  tBodyAccJerkDenergyBDZ: float
  tBodyAccJerkDiqrBDX: float
  tBodyAccJerkDiqrBDY: float
  tBodyAccJerkDiqrBDZ: float
  tBodyAccJerkDentropyBDX: float
  tBodyAccJerkDentropyBDY: float
  tBodyAccJerkDentropyBDZ: float
  tBodyAccJerkDarCoeffBDXC1: float
  tBodyAccJerkDarCoeffBDXC2: float
  tBodyAccJerkDarCoeffBDXC3: float
  tBodyAccJerkDarCoeffBDXC4: float
  tBodyAccJerkDarCoeffBDYC1: float
  tBodyAccJerkDarCoeffBDYC2: float
  tBodyAccJerkDarCoeffBDYC3: float
  tBodyAccJerkDarCoeffBDYC4: float
  tBodyAccJerkDarCoeffBDZC1: float
  tBodyAccJerkDarCoeffBDZC2: float
  tBodyAccJerkDarCoeffBDZC3: float
  tBodyAccJerkDarCoeffBDZC4: float
  tBodyAccJerkDcorrelationBDXCY: float
  tBodyAccJerkDcorrelationBDXCZ: float
  tBodyAccJerkDcorrelationBDYCZ: float
  tBodyGyroDmeanBDX: float
  tBodyGyroDmeanBDY: float
  tBodyGyroDmeanBDZ: float
  tBodyGyroDstdBDX: float
  tBodyGyroDstdBDY: float
  tBodyGyroDstdBDZ: float
  tBodyGyroDmadBDX: float
  tBodyGyroDmadBDY: float
  tBodyGyroDmadBDZ: float
  tBodyGyroDmaxBDX: float
  tBodyGyroDmaxBDY: float
  tBodyGyroDmaxBDZ: float
  tBodyGyroDminBDX: float
  tBodyGyroDminBDY: float
  tBodyGyroDminBDZ: float
  tBodyGyroDsmaB:   float
  tBodyGyroDenergyBDX: float
  tBodyGyroDenergyBDY: float
  tBodyGyroDenergyBDZ: float
  tBodyGyroDiqrBDX: float
  tBodyGyroDiqrBDY: float
  tBodyGyroDiqrBDZ: float
  tBodyGyroDentropyBDX: float
  tBodyGyroDentropyBDY: float
  tBodyGyroDentropyBDZ: float
  tBodyGyroDarCoeffBDXC1: float
  tBodyGyroDarCoeffBDXC2: float
  tBodyGyroDarCoeffBDXC3: float
  tBodyGyroDarCoeffBDXC4: float
  tBodyGyroDarCoeffBDYC1: float
  tBodyGyroDarCoeffBDYC2: float
  tBodyGyroDarCoeffBDYC3: float
  tBodyGyroDarCoeffBDYC4: float
  tBodyGyroDarCoeffBDZC1: float
  tBodyGyroDarCoeffBDZC2: float
  tBodyGyroDarCoeffBDZC3: float
  tBodyGyroDarCoeffBDZC4: float
  tBodyGyroDcorrelationBDXCY: float
  tBodyGyroDcorrelationBDXCZ: float
  tBodyGyroDcorrelationBDYCZ: float
  tBodyGyroJerkDmeanBDX: float
  tBodyGyroJerkDmeanBDY: float
  tBodyGyroJerkDmeanBDZ: float
  tBodyGyroJerkDstdBDX: float
  tBodyGyroJerkDstdBDY: float
  tBodyGyroJerkDstdBDZ: float
  tBodyGyroJerkDmadBDX: float
  tBodyGyroJerkDmadBDY: float
  tBodyGyroJerkDmadBDZ: float
  tBodyGyroJerkDmaxBDX: float
  tBodyGyroJerkDmaxBDY: float
  tBodyGyroJerkDmaxBDZ: float
  tBodyGyroJerkDminBDX: float
  tBodyGyroJerkDminBDY: float
  tBodyGyroJerkDminBDZ: float
  tBodyGyroJerkDsmaB: float
  tBodyGyroJerkDenergyBDX: float
  tBodyGyroJerkDenergyBDY: float
  tBodyGyroJerkDenergyBDZ: float
  tBodyGyroJerkDiqrBDX: float
  tBodyGyroJerkDiqrBDY: float
  tBodyGyroJerkDiqrBDZ: float
  tBodyGyroJerkDentropyBDX: float
  tBodyGyroJerkDentropyBDY: float
  tBodyGyroJerkDentropyBDZ: float
  tBodyGyroJerkDarCoeffBDXC1: float
  tBodyGyroJerkDarCoeffBDXC2: float
  tBodyGyroJerkDarCoeffBDXC3: float
  tBodyGyroJerkDarCoeffBDXC4: float
  tBodyGyroJerkDarCoeffBDYC1: float
  tBodyGyroJerkDarCoeffBDYC2: float
  tBodyGyroJerkDarCoeffBDYC3: float
  tBodyGyroJerkDarCoeffBDYC4: float
  tBodyGyroJerkDarCoeffBDZC1: float
  tBodyGyroJerkDarCoeffBDZC2: float
  tBodyGyroJerkDarCoeffBDZC3: float
  tBodyGyroJerkDarCoeffBDZC4: float
  tBodyGyroJerkDcorrelationBDXCY: float
  tBodyGyroJerkDcorrelationBDXCZ: float
  tBodyGyroJerkDcorrelationBDYCZ: float
  tBodyAccMagDmeanB: float
  tBodyAccMagDstdB: float
  tBodyAccMagDmadB: float
  tBodyAccMagDmaxB: float
  tBodyAccMagDminB: float
  tBodyAccMagDsmaB: float
  tBodyAccMagDenergyB: float
  tBodyAccMagDiqrB: float
  tBodyAccMagDentropyB: float
  tBodyAccMagDarCoeffB1: float
  tBodyAccMagDarCoeffB2: float
  tBodyAccMagDarCoeffB3: float
  tBodyAccMagDarCoeffB4: float
  tGravityAccMagDmeanB: float
  tGravityAccMagDstdB: float
  tGravityAccMagDmadB: float
  tGravityAccMagDmaxB: float
  tGravityAccMagDminB: float
  tGravityAccMagDsmaB: float
  tGravityAccMagDenergyB: float
  tGravityAccMagDiqrB: float
  tGravityAccMagDentropyB: float
  tGravityAccMagDarCoeffB1: float
  tGravityAccMagDarCoeffB2: float
  tGravityAccMagDarCoeffB3: float
  tGravityAccMagDarCoeffB4: float
  tBodyAccJerkMagDmeanB: float
  tBodyAccJerkMagDstdB: float
  tBodyAccJerkMagDmadB: float
  tBodyAccJerkMagDmaxB: float
  tBodyAccJerkMagDminB: float
  tBodyAccJerkMagDsmaB: float
  tBodyAccJerkMagDenergyB: float
  tBodyAccJerkMagDiqrB: float
  tBodyAccJerkMagDentropyB: float
  tBodyAccJerkMagDarCoeffB1: float
  tBodyAccJerkMagDarCoeffB2: float
  tBodyAccJerkMagDarCoeffB3: float
  tBodyAccJerkMagDarCoeffB4: float
  tBodyGyroMagDmeanB: float
  tBodyGyroMagDstdB: float
  tBodyGyroMagDmadB: float
  tBodyGyroMagDmaxB: float
  tBodyGyroMagDminB: float
  tBodyGyroMagDsmaB: float
  tBodyGyroMagDenergyB: float
  tBodyGyroMagDiqrB: float
  tBodyGyroMagDentropyB: float
  tBodyGyroMagDarCoeffB1: float
  tBodyGyroMagDarCoeffB2: float
  tBodyGyroMagDarCoeffB3: float
  tBodyGyroMagDarCoeffB4: float
  tBodyGyroJerkMagDmeanB: float
  tBodyGyroJerkMagDstdB: float
  tBodyGyroJerkMagDmadB: float
  tBodyGyroJerkMagDmaxB: float
  tBodyGyroJerkMagDminB: float
  tBodyGyroJerkMagDsmaB: float
  tBodyGyroJerkMagDenergyB: float
  tBodyGyroJerkMagDiqrB: float
  tBodyGyroJerkMagDentropyB: float
  tBodyGyroJerkMagDarCoeffB1: float
  tBodyGyroJerkMagDarCoeffB2: float
  tBodyGyroJerkMagDarCoeffB3: float
  tBodyGyroJerkMagDarCoeffB4: float
  fBodyAccDmeanBDX: float
  fBodyAccDmeanBDY: float
  fBodyAccDmeanBDZ: float
  fBodyAccDstdBDX: float
  fBodyAccDstdBDY: float
  fBodyAccDstdBDZ: float
  fBodyAccDmadBDX: float
  fBodyAccDmadBDY: float
  fBodyAccDmadBDZ: float
  fBodyAccDmaxBDX: float
  fBodyAccDmaxBDY: float
  fBodyAccDmaxBDZ: float
  fBodyAccDminBDX: float
  fBodyAccDminBDY: float
  fBodyAccDminBDZ: float
  fBodyAccDsmaB: float
  fBodyAccDenergyBDX: float
  fBodyAccDenergyBDY: float
  fBodyAccDenergyBDZ: float
  fBodyAccDiqrBDX: float
  fBodyAccDiqrBDY: float
  fBodyAccDiqrBDZ: float
  fBodyAccDentropyBDX: float
  fBodyAccDentropyBDY: float
  fBodyAccDentropyBDZ: float
  fBodyAccDmaxIndsDX: float
  fBodyAccDmaxIndsDY: float
  fBodyAccDmaxIndsDZ: float
  fBodyAccDmeanFreqBDX: float
  fBodyAccDmeanFreqBDY: float
  fBodyAccDmeanFreqBDZ: float
  fBodyAccDskewnessBDX: float
  fBodyAccDkurtosisBDX: float
  fBodyAccDskewnessBDY: float
  fBodyAccDkurtosisBDY: float
  fBodyAccDskewnessBDZ: float
  fBodyAccDkurtosisBDZ: float
  fBodyAccDbandsEnergyBD1C8: float
  fBodyAccDbandsEnergyBD9C16: float
  fBodyAccDbandsEnergyBD17C24: float
  fBodyAccDbandsEnergyBD25C32: float
  fBodyAccDbandsEnergyBD33C40: float
  fBodyAccDbandsEnergyBD41C48: float
  fBodyAccDbandsEnergyBD49C56: float
  fBodyAccDbandsEnergyBD57C64: float
  fBodyAccDbandsEnergyBD1C16: float
  fBodyAccDbandsEnergyBD17C32: float
  fBodyAccDbandsEnergyBD33C48: float
  fBodyAccDbandsEnergyBD49C64: float
  fBodyAccDbandsEnergyBD1C24: float
  fBodyAccDbandsEnergyBD25C48: float
  fBodyAccDbandsEnergyBD1C8P1: float
  fBodyAccDbandsEnergyBD9C16P1: float
  fBodyAccDbandsEnergyBD17C24P1: float
  fBodyAccDbandsEnergyBD25C32P1: float
  fBodyAccDbandsEnergyBD33C40P1: float
  fBodyAccDbandsEnergyBD41C48P1: float
  fBodyAccDbandsEnergyBD49C56P1: float
  fBodyAccDbandsEnergyBD57C64P1: float
  fBodyAccDbandsEnergyBD1C16P1: float
  fBodyAccDbandsEnergyBD17C32P1: float
  fBodyAccDbandsEnergyBD33C48P1: float
  fBodyAccDbandsEnergyBD49C64P1: float
  fBodyAccDbandsEnergyBD1C24P1: float
  fBodyAccDbandsEnergyBD25C48P1: float
  fBodyAccDbandsEnergyBD1C8P2: float
  fBodyAccDbandsEnergyBD9C16P2: float
  fBodyAccDbandsEnergyBD17C24P2: float
  fBodyAccDbandsEnergyBD25C32P2: float
  fBodyAccDbandsEnergyBD33C40P2: float
  fBodyAccDbandsEnergyBD41C48P2: float
  fBodyAccDbandsEnergyBD49C56P2: float
  fBodyAccDbandsEnergyBD57C64P2: float
  fBodyAccDbandsEnergyBD1C16P2: float
  fBodyAccDbandsEnergyBD17C32P2: float
  fBodyAccDbandsEnergyBD33C48P2: float
  fBodyAccDbandsEnergyBD49C64P2: float
  fBodyAccDbandsEnergyBD1C24P2: float
  fBodyAccDbandsEnergyBD25C48P2: float
  fBodyAccJerkDmeanBDX: float
  fBodyAccJerkDmeanBDY: float
  fBodyAccJerkDmeanBDZ: float
  fBodyAccJerkDstdBDX: float
  fBodyAccJerkDstdBDY: float
  fBodyAccJerkDstdBDZ: float
  fBodyAccJerkDmadBDX: float
  fBodyAccJerkDmadBDY: float
  fBodyAccJerkDmadBDZ: float
  fBodyAccJerkDmaxBDX: float
  fBodyAccJerkDmaxBDY: float
  fBodyAccJerkDmaxBDZ: float
  fBodyAccJerkDminBDX: float
  fBodyAccJerkDminBDY: float
  fBodyAccJerkDminBDZ: float
  fBodyAccJerkDsmaB: float
  fBodyAccJerkDenergyBDX: float
  fBodyAccJerkDenergyBDY: float
  fBodyAccJerkDenergyBDZ: float
  fBodyAccJerkDiqrBDX: float
  fBodyAccJerkDiqrBDY: float
  fBodyAccJerkDiqrBDZ: float
  fBodyAccJerkDentropyBDX: float
  fBodyAccJerkDentropyBDY: float
  fBodyAccJerkDentropyBDZ: float
  fBodyAccJerkDmaxIndsDX: float
  fBodyAccJerkDmaxIndsDY: float
  fBodyAccJerkDmaxIndsDZ: float
  fBodyAccJerkDmeanFreqBDX: float
  fBodyAccJerkDmeanFreqBDY: float
  fBodyAccJerkDmeanFreqBDZ: float
  fBodyAccJerkDskewnessBDX: float
  fBodyAccJerkDkurtosisBDX: float
  fBodyAccJerkDskewnessBDY: float
  fBodyAccJerkDkurtosisBDY: float
  fBodyAccJerkDskewnessBDZ: float
  fBodyAccJerkDkurtosisBDZ: float
  fBodyAccJerkDbandsEnergyBD1C8: float
  fBodyAccJerkDbandsEnergyBD9C16: float
  fBodyAccJerkDbandsEnergyBD17C24: float
  fBodyAccJerkDbandsEnergyBD25C32: float
  fBodyAccJerkDbandsEnergyBD33C40: float
  fBodyAccJerkDbandsEnergyBD41C48: float
  fBodyAccJerkDbandsEnergyBD49C56: float
  fBodyAccJerkDbandsEnergyBD57C64: float
  fBodyAccJerkDbandsEnergyBD1C16: float
  fBodyAccJerkDbandsEnergyBD17C32: float
  fBodyAccJerkDbandsEnergyBD33C48: float
  fBodyAccJerkDbandsEnergyBD49C64: float
  fBodyAccJerkDbandsEnergyBD1C24: float
  fBodyAccJerkDbandsEnergyBD25C48: float
  fBodyAccJerkDbandsEnergyBD1C8P1: float
  fBodyAccJerkDbandsEnergyBD9C16P1: float
  fBodyAccJerkDbandsEnergyBD17C24P1: float
  fBodyAccJerkDbandsEnergyBD25C32P1: float
  fBodyAccJerkDbandsEnergyBD33C40P1: float
  fBodyAccJerkDbandsEnergyBD41C48P1: float
  fBodyAccJerkDbandsEnergyBD49C56P1: float
  fBodyAccJerkDbandsEnergyBD57C64P1: float
  fBodyAccJerkDbandsEnergyBD1C16P1: float
  fBodyAccJerkDbandsEnergyBD17C32P1: float
  fBodyAccJerkDbandsEnergyBD33C48P1: float
  fBodyAccJerkDbandsEnergyBD49C64P1: float
  fBodyAccJerkDbandsEnergyBD1C24P1: float
  fBodyAccJerkDbandsEnergyBD25C48P1: float
  fBodyAccJerkDbandsEnergyBD1C8P2: float
  fBodyAccJerkDbandsEnergyBD9C16P2: float
  fBodyAccJerkDbandsEnergyBD17C24P2: float
  fBodyAccJerkDbandsEnergyBD25C32P2: float
  fBodyAccJerkDbandsEnergyBD33C40P2: float
  fBodyAccJerkDbandsEnergyBD41C48P2: float
  fBodyAccJerkDbandsEnergyBD49C56P2: float
  fBodyAccJerkDbandsEnergyBD57C64P2: float
  fBodyAccJerkDbandsEnergyBD1C16P2: float
  fBodyAccJerkDbandsEnergyBD17C32P2: float
  fBodyAccJerkDbandsEnergyBD33C48P2: float
  fBodyAccJerkDbandsEnergyBD49C64P2: float
  fBodyAccJerkDbandsEnergyBD1C24P2: float
  fBodyAccJerkDbandsEnergyBD25C48P2: float
  fBodyGyroDmeanBDX: float
  fBodyGyroDmeanBDY: float
  fBodyGyroDmeanBDZ: float
  fBodyGyroDstdBDX: float
  fBodyGyroDstdBDY: float
  fBodyGyroDstdBDZ: float
  fBodyGyroDmadBDX: float
  fBodyGyroDmadBDY: float
  fBodyGyroDmadBDZ: float
  fBodyGyroDmaxBDX: float
  fBodyGyroDmaxBDY: float
  fBodyGyroDmaxBDZ: float
  fBodyGyroDminBDX: float
  fBodyGyroDminBDY: float
  fBodyGyroDminBDZ: float
  fBodyGyroDsmaB: float
  fBodyGyroDenergyBDX: float
  fBodyGyroDenergyBDY: float
  fBodyGyroDenergyBDZ: float
  fBodyGyroDiqrBDX: float
  fBodyGyroDiqrBDY: float
  fBodyGyroDiqrBDZ: float
  fBodyGyroDentropyBDX: float
  fBodyGyroDentropyBDY: float
  fBodyGyroDentropyBDZ: float
  fBodyGyroDmaxIndsDX: float
  fBodyGyroDmaxIndsDY: float
  fBodyGyroDmaxIndsDZ: float
  fBodyGyroDmeanFreqBDX: float
  fBodyGyroDmeanFreqBDY: float
  fBodyGyroDmeanFreqBDZ: float
  fBodyGyroDskewnessBDX: float
  fBodyGyroDkurtosisBDX: float
  fBodyGyroDskewnessBDY: float
  fBodyGyroDkurtosisBDY: float
  fBodyGyroDskewnessBDZ: float
  fBodyGyroDkurtosisBDZ: float
  fBodyGyroDbandsEnergyBD1C8: float
  fBodyGyroDbandsEnergyBD9C16: float
  fBodyGyroDbandsEnergyBD17C24: float
  fBodyGyroDbandsEnergyBD25C32: float
  fBodyGyroDbandsEnergyBD33C40: float
  fBodyGyroDbandsEnergyBD41C48: float
  fBodyGyroDbandsEnergyBD49C56: float
  fBodyGyroDbandsEnergyBD57C64: float
  fBodyGyroDbandsEnergyBD1C16: float
  fBodyGyroDbandsEnergyBD17C32: float
  fBodyGyroDbandsEnergyBD33C48: float
  fBodyGyroDbandsEnergyBD49C64: float
  fBodyGyroDbandsEnergyBD1C24: float
  fBodyGyroDbandsEnergyBD25C48: float
  fBodyGyroDbandsEnergyBD1C8P1: float
  fBodyGyroDbandsEnergyBD9C16P1: float
  fBodyGyroDbandsEnergyBD17C24P1: float
  fBodyGyroDbandsEnergyBD25C32P1: float
  fBodyGyroDbandsEnergyBD33C40P1: float
  fBodyGyroDbandsEnergyBD41C48P1: float
  fBodyGyroDbandsEnergyBD49C56P1: float
  fBodyGyroDbandsEnergyBD57C64P1: float
  fBodyGyroDbandsEnergyBD1C16P1: float
  fBodyGyroDbandsEnergyBD17C32P1: float
  fBodyGyroDbandsEnergyBD33C48P1: float
  fBodyGyroDbandsEnergyBD49C64P1: float
  fBodyGyroDbandsEnergyBD1C24P1: float
  fBodyGyroDbandsEnergyBD25C48P1: float
  fBodyGyroDbandsEnergyBD1C8P2: float
  fBodyGyroDbandsEnergyBD9C16P2: float
  fBodyGyroDbandsEnergyBD17C24P2: float
  fBodyGyroDbandsEnergyBD25C32P2: float
  fBodyGyroDbandsEnergyBD33C40P2: float
  fBodyGyroDbandsEnergyBD41C48P2: float
  fBodyGyroDbandsEnergyBD49C56P2: float
  fBodyGyroDbandsEnergyBD57C64P2: float
  fBodyGyroDbandsEnergyBD1C16P2: float
  fBodyGyroDbandsEnergyBD17C32P2: float
  fBodyGyroDbandsEnergyBD33C48P2: float
  fBodyGyroDbandsEnergyBD49C64P2: float
  fBodyGyroDbandsEnergyBD1C24P2: float
  fBodyGyroDbandsEnergyBD25C48P2: float
  fBodyAccMagDmeanB: float
  fBodyAccMagDstdB: float
  fBodyAccMagDmadB: float
  fBodyAccMagDmaxB: float
  fBodyAccMagDminB: float
  fBodyAccMagDsmaB: float
  fBodyAccMagDenergyB: float
  fBodyAccMagDiqrB: float
  fBodyAccMagDentropyB: float
  fBodyAccMagDmaxInds: float
  fBodyAccMagDmeanFreqB: float
  fBodyAccMagDskewnessB: float
  fBodyAccMagDkurtosisB: float
  fBodyBodyAccJerkMagDmeanB: float
  fBodyBodyAccJerkMagDstdB: float
  fBodyBodyAccJerkMagDmadB: float
  fBodyBodyAccJerkMagDmaxB: float
  fBodyBodyAccJerkMagDminB: float
  fBodyBodyAccJerkMagDsmaB: float
  fBodyBodyAccJerkMagDenergyB: float
  fBodyBodyAccJerkMagDiqrB: float
  fBodyBodyAccJerkMagDentropyB: float
  fBodyBodyAccJerkMagDmaxInds: float
  fBodyBodyAccJerkMagDmeanFreqB: float
  fBodyBodyAccJerkMagDskewnessB: float
  fBodyBodyAccJerkMagDkurtosisB: float
  fBodyBodyGyroMagDmeanB: float
  fBodyBodyGyroMagDstdB: float
  fBodyBodyGyroMagDmadB: float
  fBodyBodyGyroMagDmaxB: float
  fBodyBodyGyroMagDminB: float
  fBodyBodyGyroMagDsmaB: float
  fBodyBodyGyroMagDenergyB: float
  fBodyBodyGyroMagDiqrB: float
  fBodyBodyGyroMagDentropyB: float
  fBodyBodyGyroMagDmaxInds: float
  fBodyBodyGyroMagDmeanFreqB: float
  fBodyBodyGyroMagDskewnessB: float
  fBodyBodyGyroMagDkurtosisB: float
  fBodyBodyGyroJerkMagDmeanB: float
  fBodyBodyGyroJerkMagDstdB: float
  fBodyBodyGyroJerkMagDmadB: float
  fBodyBodyGyroJerkMagDmaxB: float
  fBodyBodyGyroJerkMagDminB: float
  fBodyBodyGyroJerkMagDsmaB: float
  fBodyBodyGyroJerkMagDenergyB: float
  fBodyBodyGyroJerkMagDiqrB: float
  fBodyBodyGyroJerkMagDentropyB: float
  fBodyBodyGyroJerkMagDmaxInds: float
  fBodyBodyGyroJerkMagDmeanFreqB: float
  fBodyBodyGyroJerkMagDskewnessB: float
  fBodyBodyGyroJerkMagDkurtosisB: float
  angleStBodyAccMeanCgravityE: float
  angleStBodyAccJerkMeanCgravityMeanE: float
  angleStBodyGyroMeanCgravityMeanE: float
  angleStBodyGyroJerkMeanCgravityMeanE: float
  angleSXCgravityMeanE: float
  angleSYCgravityMeanE: float
  angleSZCgravityMeanE: float
  subject: int
